version: "3.9"
services:
  nginx:
    build: frontend
    ports:
      - "8000:80"
  mysql:
    build: backend/db
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polysoutenance
  api:
    build: backend/api