# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-frontend:
    defaults:
      run:
        working-directory: 'frontend'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NodeJS 18.10.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.10.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install Dependencies
      run: npm ci
    - name: Make pretty
      run: npm run pretty
    - name: Build project
      run: npm run build --if-present
    #TODO: Uncomment when tests are present
    #- name: Test project
    #run: npm run test:headless
    
  build-backend:
    defaults:
      run:
        working-directory: 'backend'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NodeJS 18.10.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.10.x
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Install Dependencies
      run: npm ci
    - name: Make pretty
      run: npm run pretty
    - name: Build project
      run: npm run build --if-present
    #TODO: Uncomment when Tests are present
    #- name: Test project
    #  run: npm test --if-present
